# Generated by Django 4.0.2 on 2022-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=60, unique=True, verbose_name='phone-number'),
        ),
    ]
